use std::{fmt, fmt::Write as _};

const DEFAULT_AGENTS: &[&str] = &["codex", "claude", "pi", "omp", "hermes"];

#[derive(Debug)]
pub enum ShellError {
    InvalidAgent(String),
}

impl fmt::Display for ShellError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidAgent(agent) => write!(
                formatter,
                "invalid agent command {agent:?}; shell wrappers require a simple command name"
            ),
        }
    }
}

pub fn render(agents: &[String]) -> Result<String, ShellError> {
    let agents = if agents.is_empty() {
        DEFAULT_AGENTS
            .iter()
            .map(|agent| (*agent).to_owned())
            .collect::<Vec<_>>()
    } else {
        agents.to_vec()
    };
    for agent in &agents {
        if !valid_function_name(agent) {
            return Err(ShellError::InvalidAgent(agent.clone()));
        }
    }

    let mut script = String::from(
        r#"# Rollcall agent launch shim for Bash and Zsh.
# Generated by `rollcall shell-init`; source or eval this output.

_rollcall_agent_binary() {
  if [ -n "${BASH_VERSION-}" ]; then
    type -P -- "$1"
  elif [ -n "${ZSH_VERSION-}" ]; then
    whence -p -- "$1"
  else
    command -v -- "$1"
  fi
}

_rollcall_session_slug() {
  local value slug
  value="${1:-session}"
  slug="$(
    printf '%s' "$value" |
      LC_ALL=C tr '[:upper:]' '[:lower:]' |
      LC_ALL=C tr -cs 'a-z0-9' '-' |
      sed 's/^-//; s/-$//' |
      cut -c1-24
  )"
  printf '%s' "${slug:-session}"
}

_rollcall_agent() {
  local agent="$1" binary project nonce session
  shift
  binary="$(_rollcall_agent_binary "$agent")"
  if [ -z "$binary" ]; then
    printf 'rollcall: could not find the real %s executable\n' "$agent" >&2
    return 127
  fi

  if [ -n "${TMUX-}" ] ||
     [ "${ROLLCALL_BYPASS-}" = 1 ] ||
     { [ "${ROLLCALL_FORCE_WRAP-}" != 1 ] && { [ ! -t 0 ] || [ ! -t 1 ]; }; } ||
     ! command -v tmux >/dev/null 2>&1; then
    "$binary" "$@"
    return
  fi

  project="$(_rollcall_session_slug "${PWD##*/}")"
  nonce="$(date +%s)-$$"
  session="rc-pending-${project}-${nonce}"
  command tmux new-session -s "$session" -c "$PWD" "$binary" "$@"
}

"#,
    );

    for agent in agents {
        writeln!(script, "unalias {agent} 2>/dev/null || true")
            .expect("writing to a string cannot fail");
        writeln!(script, "{agent}() {{ _rollcall_agent {agent} \"$@\"; }}\n")
            .expect("writing to a string cannot fail");
    }

    Ok(script)
}

fn valid_function_name(agent: &str) -> bool {
    let mut characters = agent.chars();
    matches!(characters.next(), Some(first) if first == '_' || first.is_ascii_alphabetic())
        && characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        io::Write,
        os::unix::fs::PermissionsExt,
        path::Path,
        process::{Command, Stdio},
    };

    use tempfile::tempdir;

    use super::render;

    #[test]
    fn default_shell_init_defines_each_wrapper() {
        let script = render(&[]).expect("default shell script should render");
        let output = Command::new("bash")
            .args([
                "-c",
                &format!("{script}\ntype -t codex claude pi omp hermes"),
            ])
            .output()
            .expect("bash should start");
        assert!(output.status.success());
        assert_eq!(
            String::from_utf8(output.stdout).unwrap(),
            "function\n".repeat(5)
        );
    }

    #[test]
    fn custom_agent_names_are_validated_before_rendering() {
        assert!(render(&["codex".to_owned(), "my_agent".to_owned()]).is_ok());
        assert!(render(&["bad; command".to_owned()]).is_err());
        assert!(render(&["agent-name".to_owned()]).is_err());
    }

    #[test]
    fn generated_script_has_valid_bash_syntax() {
        let script = render(&[]).expect("default shell script should render");
        let mut child = Command::new("bash")
            .arg("-n")
            .stdin(Stdio::piped())
            .spawn()
            .expect("bash should start");
        child
            .stdin
            .take()
            .expect("bash stdin should be piped")
            .write_all(script.as_bytes())
            .expect("script should be written");

        assert!(child.wait().expect("bash should finish").success());
    }

    #[test]
    fn generated_wrapper_preserves_agent_arguments_inside_tmux_launch() {
        let directory = tempdir().expect("temporary directory should exist");
        let log = directory.path().join("calls");
        write_executable(
            &directory.path().join("codex"),
            "#!/bin/sh\nprintf 'agent:%s\\n' \"$*\" >> \"$ROLLCALL_TEST_LOG\"\n",
        );
        write_executable(
            &directory.path().join("tmux"),
            "#!/bin/sh\nprintf 'tmux:' >> \"$ROLLCALL_TEST_LOG\"\nprintf '<%s>' \"$@\" >> \"$ROLLCALL_TEST_LOG\"\nprintf '\\n' >> \"$ROLLCALL_TEST_LOG\"\n",
        );
        let script = render(&["codex".to_owned()]).expect("script should render");
        let command = format!("{script}\nROLLCALL_FORCE_WRAP=1 codex --model 'gpt test'");
        let path = format!(
            "{}:{}",
            directory.path().display(),
            std::env::var("PATH").unwrap_or_default()
        );
        let status = Command::new("bash")
            .args(["-c", &command])
            .env_remove("TMUX")
            .env_remove("ROLLCALL_BYPASS")
            .env("PATH", path)
            .env("ROLLCALL_TEST_LOG", &log)
            .status()
            .expect("generated wrapper should run");

        assert!(status.success());
        let calls = fs::read_to_string(log).expect("tmux call should be logged");
        assert!(calls.starts_with("tmux:<new-session><-s><rc-pending-"));
        assert!(calls.contains("<-c>"));
        assert!(calls.contains("<--model><gpt test>"));
        assert!(!calls.contains("agent:"));
    }

    #[test]
    fn bypass_runs_the_real_agent_without_tmux() {
        let directory = tempdir().expect("temporary directory should exist");
        let log = directory.path().join("calls");
        write_executable(
            &directory.path().join("codex"),
            "#!/bin/sh\nprintf 'agent:<%s><%s>\\n' \"$1\" \"$2\" >> \"$ROLLCALL_TEST_LOG\"\n",
        );
        write_executable(
            &directory.path().join("tmux"),
            "#!/bin/sh\nprintf 'tmux\\n' >> \"$ROLLCALL_TEST_LOG\"\n",
        );
        let script = render(&["codex".to_owned()]).expect("script should render");
        let command =
            format!("{script}\nROLLCALL_FORCE_WRAP=1 ROLLCALL_BYPASS=1 codex --model 'gpt test'");
        let path = format!(
            "{}:{}",
            directory.path().display(),
            std::env::var("PATH").unwrap_or_default()
        );
        let status = Command::new("bash")
            .args(["-c", &command])
            .env_remove("TMUX")
            .env("PATH", path)
            .env("ROLLCALL_TEST_LOG", &log)
            .status()
            .expect("generated wrapper should run");

        assert!(status.success());
        assert_eq!(
            fs::read_to_string(log).expect("agent call should be logged"),
            "agent:<--model><gpt test>\n"
        );
    }

    fn write_executable(path: &Path, contents: &str) {
        fs::write(path, contents).expect("test executable should be written");
        let mut permissions = fs::metadata(path)
            .expect("test executable should exist")
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions).expect("test executable should become executable");
    }
}
